### ISSUE TITLE
"Ouch face fix" actually shows ouch face upon every instance of damage

### ISSUE THREAD

**Issue by maxmanium** [AXDOOMER/doom-patcher#3]
See title.

**Comment by AXDOOMER** [comment]
Thanks for opening an issue. I'll look into this.

**Comment by AXDOOMER** [comment]
The current patch was deeply flawed.  While it didn't fix the ouch face when the player was damaging itself, it broke the ouch face further by always showing it when the player is damaged by monsters. I'm not sure if it was the intention of the author of the patch (discussed in [this](https://www.doomworld.com/forum/topic/36097-doom2-v192-no-more-visplanes-and-drawsegs-overflows/?page=5) thread). 

The new patch is:
```
OUCHFACE = [
#	Face priority when damage is dealt from monsters. Normal is 7, higher is 8. 
#	Otherwise, the ouch face is only shown for a single frame. 
	[0x0007C088, 0x07, 0x08],
#	Fix ouch face when monsters attacked
	[0x0007C08D, 0xFA, 0xD7],
	[0x0007C095, 0xFA, 0xFF],
#	Fix ouch face when attacked self
	[0x0007C144, 0xD0, 0xC2],
	[0x0007C146, 0xF8, 0xFA]
]
```

There's an issue left with the directional damage dealt by ennemies. The directional damage has priority over the ouch face, so sometimes the ouch face isn't shown when the player is damaged from an angle. The directional damage should have a priority of 7 and the ouch face a priority of 8 in order to fix this entirely, but this would require moving a lot of code because I'd need to add more code to handle this (it's near the start of a lengthy function and moving compiled code is not an easy task). Crispy Doom had a [similar issue](https://github.com/fabiangreffrath/crispy-doom/issues/371) which [was fixed this way](https://github.com/fabiangreffrath/crispy-doom/commit/3def687811e8dee18c725cdc6b3f65608d4edbf5). 

Here's an executable with this single patch applied, so you can try it out:
[patched-exe.zip](https://github.com/AXDOOMER/doom-patcher/files/6774127/patched-exe.zip)

I hope it's satisfactory.

**Comment by maxmanium** [comment]
That exe actually seems to work perfectly -- even directionally it shows the ouch face beforehand.
